// UI strings. The site is English-only; entries display as authored.
export const strings = {
	navHome: 'Home',
	navDiary: 'Diary',
	navAbout: 'About',
	diaryHeading: 'Diary',
	newEntry: '+ New entry',
	noEntries: 'No entries yet. Log in to write the first one.',
	newEntryHeading: 'New entry',
	logout: 'Log out',
	fieldTitle: 'Title',
	fieldDate: 'Date',
	fieldBody: 'Body',
	markdownHint: '(Markdown supported)',
	publish: 'Publish',
	save: 'Save changes',
	edit: 'Edit',
	editHeading: 'Edit entry',
	errMissing: 'Title and body are both required.',
	errDate: 'That date is not valid.',
	lastUpdated: 'Last updated on',
	login: 'Log in',
	loginError: 'Incorrect username or password.',
	fieldUsername: 'Username',
	fieldPassword: 'Password',
	navTodos: 'Todos',
	todosHeading: 'Todos',
	newTodo: '+ New todo',
	newTodoHeading: 'New todo',
	editTodoHeading: 'Edit todo',
	noTodos: 'No todos yet. Add one from the template.',
	openSection: 'Open',
	completedSection: 'Completed',
	openEstimate: 'Open estimate',
	markDone: 'Mark done',
	reopen: 'Reopen',
	deleteLabel: 'Delete',
	jsonHint: 'Edit the JSON template below (a single todo or an array), then submit.',
	fieldGoal: 'Goal',
	fieldEstimate: 'Estimate',
	fieldPriority: 'Priority',
	fieldIdeas: 'Ideas',
	fieldSteps: 'Steps',
	fieldNotes: 'Notes',
	hoursSuffix: 'h',
	errInvalidJson: "That isn't valid JSON. Please fix it and try again.",
	errTodoTitle: 'Each todo needs a title.',
	weekView: 'Week view',
	listView: 'List view',
	unscheduled: 'Unscheduled',
	prevWeek: '← Previous',
	nextWeek: 'Next →',
	thisWeek: 'This week',
	dragHint: 'Drag a step onto a day to schedule it. Drag back to Unscheduled to clear.',
	noSteps: 'No steps yet. Add steps to a todo, then schedule them here.',
} as const;
